export const pages = {
  HOME: '/',
  PROFILE: '/profile/common',
  AGREGATOR: '/profile/agregator',
  UIKIT: '/uikit',
  LOGIN: '/login',
  REGISTRATION: '/registration',
  PAYMENTS: '/payments/',
  PAYMENT: '/payment/:id',
  DRIVER: '/drivers/:id',
  DRIVERS: '/drivers',
  TRIP: '/trip/:id',
  TRAVELLCHECK: '/profile/travellCheck',
  COMMISSIONS: '/profile/commissions',
  GROUPS: '/groups',
  GroupId: '/group/:id',
  Recovery: '/recovery',
  ResetPassword: '/reset-password/:token',
  TRIPTOCHECK: '/triptocheck/',
  TRAVELHISTORY: '/travelhistory/',
  TwoFA: '/profile/TwoFA',
  OnApproval: '/onApproval',
}
